# Generated by Django 5.2.12 on 2026-03-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('ticket_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('featured', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
