# Generated by Django 5.2.12 on 2026-03-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('tv', 'TV'), ('podcast', 'Podcast'), ('streaming', 'Streaming'), ('other', 'Other')], default='other', max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media_items/')),
                ('link', models.URLField(blank=True)),
                ('coming_soon', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
