name: spacious_africa
description: Spacious Africa — African entertainment platform
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/spac.png"
  web:
    generate: true
    image_path: "assets/icon/spac.png"
  macos:
    generate: true
    image_path: "assets/icon/spac.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/spac.png
