# Generated by Django 5.2.12 on 2026-03-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('musician', 'Musician'), ('actor', 'Actor'), ('actress', 'Actress'), ('director', 'Director'), ('producer', 'Producer'), ('other', 'Other')], default='musician', max_length=50)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artists/')),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('spotify_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
